include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
    require_trailing_commas: false

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
